- tests/features/amq/6.2/amq.feature
Update the banner check for AMQ62 rollup 7.
DISCLAIMER: due to the tooling changes, I have not actually managed to
run these tests at this present moment. I will of course verify them
once the dust settles.
> [CLOUD-1780] Update AMQ62 tests

- os-eap-activemq-rar/configure.sh
Adjust this script module so that it uses a glob to find the active-mq
RAR to copy into place; that way we can supply different .rar rebuild
versions without needing to modify this module further.
Signed-off-by: Jonathan Dowland <jdowland@redhat.com>
> CLOUD-1854: change active-mq cp to a glob

- tests/features/amq/6.3/amq.feature
Bump the version string for the first test.
Remove the detailed version string check for the second test; the point
of that check is as a "guard" for the steps that take place afterwards
(to make sure that we wait until start up has reached a certain point
before we try probe tests); therefore, we don't need the full version
in the check.
Signed-off-by: Jonathan Dowland <jdowland@redhat.com>
> CLOUD-1962: Update AMQ tests for 6.3 R4.

- os-eap7-launch/added/launch/messaging.sh
- tests/features/eap/7/eap_7_messaging.feature
JIRA link: https://issues.jboss.org/browse/CLOUD-1925
Currently, the JVM is not cgroup aware and cannot be trusted to generate default values for Artemis
threads pool arguments. The thread pool arguments must respect the limits of its containerized environment, and therefore are calculated using the original methods provided by Artemis and the resources reported by cgroups.
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-1925] [EAP71] Set activemq thread pool system properties

- os-kieserver-launch/added/kieserver-launch.sh
access_log_valve.sh should be executed on kieserver-launch.
> [CLOUD-1784] - Make the accessLog valve configurable

- s2i-common/common.sh
maven settings.xml generated is not correct when using domain.
If your proxy configuration include a proxy exclusion using an entire domain like this: 
NO_PROXY=.example.com,.example.net
the assemble script in /usr/local/s2i/bin/assemble translate the configuration in settings.xml like this:
<proxy>
...
<nonProxyHosts>.example.com|.example.net</nonProxyHosts>
...
</proxy>
But the correct translation is:
<proxy>
...
<nonProxyHosts>*.example.com|*.example.net</nonProxyHosts>
...
</proxy>
With the * (star) in front of the domain name.
> [CLOUD-2020] no_proxy configuration not properly translated to maven settings

- os-eap64-sso/configure.sh
- os-eap70-sso/configure.sh
7.0.0 is out-of-date. These are the latest built versions of the two
adapters available.
https://issues.jboss.org/browse/CLOUD-2061
Signed-off-by: Jonathan Dowland <jdowland@redhat.com>
> [CLOUD-2061] bump rh-sso versions

- os-jdg7-launch/added/launch/jgroups.sh
- os-jdg7-launch/configure.sh
- tests/features/datagrid/7.1/datagrid.feature
> CLOUD-2211 use SYM_ENCRYPT

- os-bpmsuite-businesscentral/added/launch/bpmsuite-businesscentral.sh
- tests/features/bpmsuite/businesscentral/configuration.feature
- tests/features/rhdm/decisioncentral/configuration.feature
This is definitely not an ideal solution. We should probably have generic set of common functions/modules and then specify which of them would be executed for the specific deliverables. But until that is in place this should be a sufficient workaround.
> [CLOUD-2221] configure KieLoginModule only for Business Central

- os-jdg7-launch/added/launch/infinispan-config.sh
- tests/features/datagrid/7.1/datagrid_compatibility_mode.feature
Issue: [CLOUD-1863](https://issues.jboss.org/browse/CLOUD-1863)
Add support for configuring compatibility mode for each configured cache through the use of env.
Creates two new env variables:
${prefix}_CACHE_PROTOCOL_COMPATIBILITY
- Optional, can be set for each configured cache. Enables/disables compatibility mode. Default is disabled, "true" will enable it.
${prefix}_CACHE_COMPATIBILITY_MARSHALLER
- Optional, can be set for each configured cache. Marshaller for use in compatibility mode, only will be considered if compatibility mode is enabled though the previous env. As of JDG 7.1, does not support the configuration of external marshallers, only internal ones (e.g. org.infinispan.commons.marshall.JavaSerializationMarshaller or …
> [CLOUD-1863] Add support for compatibility mode

- os-jdg7-launch/added/launch/jgroups.sh
- os-jdg7-launch/configure.sh
- tests/features/datagrid/7.1/datagrid.feature
The ENCRYPT protocol was deprecated and should not be used anymore.
JDG is using SYM_ENCRYPT since JDG 7.1.0.
Signed-off-by: Osni Oliveira <osni.oliveira@gmail.com>
https://issues.jboss.org/browse/CLOUD-2226
> [CLOUD-2226] Use SYM_ENCRYPT instead of ENCRYPT

- os-sso72/added/standalone-openshift.xml
Per [CLOUD-2323](https://issues.jboss.org/browse/CLOUD-2323) issue this change updates the standalone-openshift.xml configuration file for RH-SSO 7.2 for OpenShift image to be based on the form of standalone-ha.xml configuration file, as shipped within Red Hat Single Sign-On - Version 7.2.0.GA
<b>Note</b>: This is the very same change as in https://github.com/jboss-openshift/cct_module/pull/203 but also / this time against the ```master``` branch of the cct_module.
Signed-off-by: Jan Lieskovsky jlieskov@redhat.com
> [CLOUD-2323] Synchronize standalone-openshift.xml with the form of standalone-ha.xml from the Red Hat Single Sign-On - Version 7.2.0.GA

- os-eap-launch/added/launch/jgroups.sh
- os-jdg-launch/added/launch/jgroups.sh
- os-jdg-launch/configure.sh
- os-jdg7-launch/configure.sh
Cherrypick changes from https://github.com/jboss-openshift/cct_module/pull/198 also into the ```sprint-14``` branch.
> [CLOUD-2316] only use JGroups ENCRYPT protocol with JDG 6.5

- os-logging/configure.sh
- os-logging/module.yaml
Part of the fix for https://issues.jboss.org/browse/RHBA-530
Fixes https://issues.jboss.org/browse/CLOUD-2379
Allows the possibility for non-eap images to decide where to copy the scripts
> [CLOUD-2379] Allow override LAUNCH_DIR

- os-eap7-launch/added/launch/activemq-subsystem.xml
https://issues.jboss.org/browse/CLOUD-2151
Note this *removes* the embedded broker clustering, and thereby fixes the reported issue. The embedded broker clustering is not and never was officially supported.
Signed-off-by: Ken Wills <kwills@redhat.com
> CLOUD-2151 - Scaling pod down causes ActiveMQ AMQ214016 NoRouteToHost error messages

- os-sso72/added/launch/openshift-common.sh
- os-sso72/added/launch/openshift-x509.sh
- os-sso72/module.yaml
<br/>
[CLOUD-2398] Auto-generate the HTTPS and JGroups keystores if volumes for OpenShift's serving x509 certificate secrets service were properly mounted
<br/><br/>
Auto-generate the truststore for the RH-SSO server if the X509 CA bundle was provided and truststore doesn't exist yet
<br/><br/>
> [CE Sprint #16] [CLOUD-2398] Auto-generate the HTTPS, JGroups keystores, and truststore for the RH-SSO server upon request

- jboss-maven/added/jboss-settings.xml
- os-eap-launch/added/launch/maven-repos.sh
- os-java-s2i/added/s2i/jboss-settings.xml
- s2i-common/common.sh
https://issues.jboss.org/browse/CLOUD-2465
Allow custom location for local maven repository by using <localRepository> to designate a location other than the standard ~/.m2/repository
> [CLOUD-2465] Allow custom location for local maven repository

- os-eap64-launch/added/launch/jboss_modules_system_pkgs.sh
- os-eap7-launch/added/launch/jboss_modules_system_pkgs.sh
This adds com.sun.crypto.provider to JBOSS_MODULES_SYSTEM_PKGS for both EAP 7 and EAP 6.4.
https://issues.jboss.org/browse/CLOUD-2501
> CLOUD-2501 - java.io.IOException: Invalid secret key format on JCEKS keystores

- os-jdg7-launch/added/launch/openshift-common.sh
Enables JDG 7.x to use the fix for [CLOUD-2501](https://issues.jboss.org/browse/CLOUD-2501).
See #238.
> [CLOUD-2501] Add modules system pkgs script to JDG 7.x - sprint-15

- tests/features/eap/6.4/eap.feature
- tests/features/eap/7.1/eap_7_1.feature
- tests/features/eap/eap_common.feature
This addresses the EAP 6.4 and 7.1 breakage in the behave tests due to the changes in CLOUD-2501. It also updates the -docker suffix to -container. (Also, not that this is included in the list of things to revert when we drop the CLOUD-2501 workarounds in CLOUD-2506 & CLOUD-2507.)
There may be additional testing issues, I'll open up seperate tickets to address those and add support for testing EAP-CD (which I have almost completed).
https://issues.jboss.org/browse/CLOUD-2511
> CLOUD-2511 - cct_module test fixes

- README.adoc
- datagrid-openshift/module.yaml
- dynamic-resources/module.yaml
- os-amq-launch/module.yaml
- os-datavirt-s2i/module.yaml
- os-datavirt/module.yaml
- os-eap-db-drivers/module.yaml
- os-eap-launch/module.yaml
- os-eap-probes/module.yaml
- os-eap-s2i/module.yaml
- os-eap-sso/module.yaml
- os-eap64-launch/module.yaml
- os-eap64-openshift/module.yaml
- os-eap7-launch/module.yaml
- os-eap7-openshift/module.yaml
- os-java-run/module.yaml
- os-jdg-launch/module.yaml
- os-jdg7-launch/module.yaml
- os-jws-launch/module.yaml
- os-sso/module.yaml
- os-sso71/module.yaml
- os-sso72/module.yaml
Also, while at this, squeeze the double space character in descriptions of certain environment variables into single one
<b>Note:</b> Since this PR [depends on ```cct_module``` change for CLOUD-2413 made by Jonathan](https://github.com/jboss-openshift/cct_module/pull/222), it can be merged only <b>after</b> the [CLOUD-2413](https://issues.jboss.org/browse/CLOUD-2413) changes have been merged.
> [CLOUD-2514] Make description of JAVA_MAX_MEM_RATIO environment variable container runtime-agnostic. Same for README.adoc

- os-eap7-launch/added/openshift-launch.sh
https://issues.jboss.org/browse/CLOUD-2629
> [CLOUD-2629] EAP openshift-launch.sh doesn't trap INT

- .gitignore
- os-datavirt/module.yaml
- os-eap-migration/added/launch/openshift-migrate-common.sh
- os-eap-migration/module.yaml
- os-eap-probes/added/readinessProbe.sh
- os-eap64-launch/added/openshift-launch.sh
- os-eap64-launch/module.yaml
- os-eap7-launch/added/openshift-launch.sh
- os-eap7-launch/module.yaml
- os-jdg-launch/module.yaml
- os-jdg7-launch/module.yaml
- os-partition-txnrecovery/added/partitionPV.sh
- os-partition-txnrecovery/added/query.py
- os-partition-txnrecovery/configure.sh
- os-partition-txnrecovery/install_as_root.sh
- os-partition-txnrecovery/module.yaml
- os-sso71/module.yaml
- os-sso72/module.yaml
- tests/features/datagrid/datagrid_split.feature
https://issues.jboss.org/browse/CLOUD-2261
hopefully non-invasive addition of the txn recovery mechanism based on the algorithm presented at https://docs.google.com/document/d/1JdOTMP6pdexJ__KYlw9hgwR6DOCHTtYCQy7PqyMk8OU/edit which addresses issue mentioned at CLOUD-2261
/cc @rcernich
> [CLOUD-2261] handling txn recovery by querying api

- os-eap-migration/added/launch/openshift-migrate-common.sh
https://issues.jboss.org/browse/CLOUD-2767
Setting the socket timeout of the recovery request to 30 minutes while expecting whole recovery process (both phases) will be run in such time.
From the perspective of the script we need to ensure that scan is completly finished and only then server shutdown is requested.
> [CLOUD-2767] setting bigger timeout for recovery scan

- os-java-run/added/java-default-options
- os-java-run/module.yaml
- tests/features/java/gc.feature
Move hard-coded GC options into a "GC_OPTIONS" environment variable
that can be user-supplied to override the defaults.
https://issues.jboss.org/browse/CLOUD-2286
> [CLOUD-2286] permit user configuration of GC

- os-eap7-launch/added/launch/elytron.sh
https://issues.jboss.org/browse/CLOUD-2406
* Default HTTPS_KEY_PASSWORD to HTTPS_PASSWORD
* Don't require HTTPS_KEYSTORE_DIR; use jboss.server.config.dir path if not set
* If HTTPS_KEYSTORE_DIR starts with '/' treat it as an absolute path, else as config model path name
* If settings are mssing, state what they are
- [X ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ X] Pull Request contains link to the JIRA issue
- [X ] Pull Request contains description of the issue
- [X ] Pull request does not include fixes for other issues than the main ticket
- [X ] Attached commits represent unit of work and are properly formatted
- [X ] You have read and agreed to the Developer Certificate of Origin (DCO) (see …
> [CLOUD-2406] Fix and improve Elytron configuration integration

- tests/features/common.feature
[CLOUD-2905] RHBA feature tests have incorrect tagging
https://issues.jboss.org/browse/CLOUD-2905
Signed-off-by: David Ward <dward@redhat.com>
> [CLOUD-2905] RHBA feature tests have incorrect tagging

- os-amq-launch/added/drain.sh
- os-amq-launch/added/launch.sh
- tests/features/amq/amq-common.feature
> CLOUD-2821 fix http.nonProxyHosts escaping for amq

- jboss/container/java/jvm/bash/artifacts/opt/jboss/container/java/jvm/java-default-options
- jboss/container/openjdk/jdk/11/README.adoc
- jboss/container/openjdk/jdk/11/configure.sh
- jboss/container/openjdk/jdk/11/module.yaml
- jboss/container/openjdk/jdk/8/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
- jboss/container/openjdk/jdk/8/configure.sh
> CLOUD-2869 add support for building jdk 11 based images

- jboss/container/openjdk/jdk/8/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
- tests/features/java/gc.feature
UseCGroupMemoryLimitForHeap is not needed from OpenJDK
8u191 and onwards
UnlockExperimentalVMOptions was only needed to unlock
UseCGroupMemoryLimitForHeap
https://issues.jboss.org/browse/CLOUD-2985
> [CLOUD-2985] remove unnecessary JVM arguments

- jboss/container/maven/35/bash/configure.sh
- jboss/container/openjdk/jdk/11/configure.sh
- jboss/container/openjdk/jdk/8/configure.sh
http://issues.jboss.org/browse/CLOUD-3044
> CLOUD-3044 move jdk8 removal from jdk11 module to maven module

- tests/features/common.feature
[CLOUD-3065] Move base layer of RHBA 6.4 images from jboss-eap-6/eap64-openshift:1.8 to rhel7:7-released
https://issues.jboss.org/browse/CLOUD-3065
Signed-off-by: David Ward <dward@redhat.com>
> [CLOUD-3065] Move base layer of RHBA 6.4 images from jboss-eap-6/eap64-openshift:1.8 to rhel7:7-released

- jboss/container/java/s2i/bash/artifacts/opt/jboss/container/java/s2i/maven-s2i-overrides
missing '-r' meant the directory was not recursively copied.
https://issues.jboss.org/browse/SB-1172
> CLOUD-3095 fix invocation of rsync in s2i/maven path

- jboss/container/maven/default/bash/artifacts/opt/jboss/container/maven/default/maven.sh
[CLOUD-3010] maven settings script MAVEN_REPOS prefixes lowercase
https://issues.jboss.org/browse/CLOUD-3010
Signed-off-by: Petr Nehyba penehyba@redhat.com
> [CLOUD-3010] maven settings script MAVEN_REPOS prefixes lowercase

- os-jws-secure-mgmt-console/run
> [CLOUD-3168] Missing escape in context.xml sed in os-jws-secure-mgmt-console module

- openshift-layer/configure_layers.sh
https://issues.jboss.org/browse/CLOUD-3269
> [CLOUD-3269] - Don't symlink module jars if the source doesn't exist

- jboss/container/java/s2i/bash/artifacts/usr/local/s2i/run
- jboss/container/java/s2i/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3272
Remove the hawkular agent which does not work properly under OpenJDK 11, is likely not being used, the artefact has not been updated since October 2017, etc
> [CLOUD-3272] Remove hawkular agent from OpenJDK

- jboss/container/java/jvm/api/README.adoc
- jboss/container/java/jvm/api/module.yaml
- jboss/container/java/jvm/bash/artifacts/opt/jboss/container/java/jvm/java-default-options
https://issues.jboss.org/browse/CLOUD-3270
> CLOUD-3270 - There is no environment variable to configure the initial metaspace size

- jboss/container/java/rm-openjdk/configure.sh
- jboss/container/java/rm-openjdk/module.yaml
- jboss/container/openjdk/jdk/openj9-11/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
- jboss/container/openjdk/jdk/openj9-11/configure.sh
- jboss/container/openjdk/jdk/openj9-11/module.yaml
- jboss/container/openjdk/jdk/openj9-8/artifacts/opt/jboss/container/openjdk/jdk/jvm-options
- jboss/container/openjdk/jdk/openj9-8/configure.sh
- jboss/container/openjdk/jdk/openj9-8/module.yaml
A new module that installs OpenJ9 instead of OpenJDK.
Some things I'd like to fix:
> Openj9 support

- os-sso72/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-3433
Standalone-openshift.xml has the incorrect version of the io:subsystem
Signed-off-by: Daniel Kreling <dkreling@gmail.com>
> [CLOUD-3433] fix version of io:subsystem in standalone-openshift.xml

- jboss/container/maven/36/default/configure.sh
- jboss/container/maven/36/default/module.yaml
The AppStream module part of this commit is necessary to get access
to Maven 3.6 (instead of 3.5). The "dnf module enable" part needs
to happen before the package installation. Cekit's module ordering
places the "execute" last; so we either need to have two cekit
modules: the first to enable the AppStream module, and the second
to install the package; or (as in this commit) perform the package
installation in the script, too.
This hard-codes "dnf". However, "microdnf" does not support enabling
AppStream modules, which rules out using the minimal-flavour images
without further work.
> enable Maven 3.6 AppStream module prior to install

- jboss/container/maven/36/default/configure.sh
PR #366 was a little too aggressive in removing code from configure.sh
leaving this module as (almost) a no-op. Restore the maven installation
commands.
> Fix the maven 3.6 default module

- jboss/container/dnf/module.yaml
- jboss/container/microdnf-bz-workaround/configure.sh
- jboss/container/microdnf-bz-workaround/module.yaml
I'm using both of these modules in order to base on the ubi-minimal base image; I need to install DNF to enable the maven module; the BZ workaround is hopefully temporary.
> New modules for ubi-minimal

- tests/features/eap/eap_common.feature
- tests/features/sso/sso.feature
- tests/features/webserver/webserver_tomcat.feature
[CLOUD-3550] Update path of Jolokia's JVM agent JAR in existing CCT tests too
Recent 3bee8b7 change moved Jolokia's JVM agent JAR from former
"/opt/jboss/container/jolokia/jolokia.jar" path to the new
"/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar" one
Update the existing CCT module Jolokia tests too, so they expect
the new location in the pod log
> [CLOUD-3550] Update path of Jolokia's JVM agent JAR in existing CCT tests too

- jboss/container/java/s2i/bash/artifacts/opt/jboss/container/java/s2i/maven-s2i-overrides
- jboss/container/maven/api/module.yaml
https://issues.redhat.com/browse/OPENJDK-92
This is to resolve a very old (3y) issue, removing references to hawt-app that were added originally for something to do with FIS 1.0 (FIS ≥ 2 does not use hawtio, I think?)
The module YAML change is informative only; the script change has passed all the unit tests.
> OPENJDK-92: Remove old references to hawt-app

- jboss/container/java/s2i/bash/artifacts/usr/local/s2i/run
https://issues.jboss.org/browse/CLOUD-3387
don't try to enable Maven (Via SCL) in the s2i run script.
We might not have provided Maven via SCL in the image anyway.
> [CLOUD-3387] Don't attempt to enable maven in run

- tests/features/jboss/container/s2i/core/bash/s2i-core.feature
tests that we remove the contents of /tmp/src after an S2I build. The code we are testing was merged here in #375
> [OPENJDK-160] test for OPENJDK-84 (remove S2I-injected source post build)

- jboss/container/maven/8.2.3.6/configure.sh
Remove the maven.config file comes with maven 3.6 installation. This file disables the setting of $JAVA_HOME later in the container.
> Remove the maven.config file

- jboss/container/prometheus/7/artifacts/opt/jboss/container/prometheus/prometheus-opts
- jboss/container/prometheus/8.2/artifacts/opt/jboss/container/prometheus/prometheus-opts
<https://issues.redhat.com/browse/CLOUD-3484>
We were sourcing logging.sh from the module
jboss.container.util.logging.bash module but did not have a dependency
upon it. And we aren't using it anyway.
> [CLOUD-3484] Prometheus: don't import logging.sh

- jboss/container/java/run/bash/configure.sh
- jboss/container/java/run/bash/module.yaml
- tests/features/jboss/container/java/run/bash/java.security.feature
Set a system property so that we do not cache negative DNS responses for
any length of time. This can interact badly with short-lived DNS names.
We can expect DNS caching to take place at the OpenShift layer anyway.
https://issues.redhat.com/browse/OPENJDK-100
> [OPENJDK-100] set networkaddress.cache.negative.ttl=0

- jboss/container/prometheus/7/module.yaml
The new artefact contains a shaded SnakeYAML with a fix for
CVE-2017-18640.
>  Bump Prometheus agent version to pick up SnakeYAML fix

- jboss/container/maven/default/module.yaml
- jboss/container/s2i/core/bash/module.yaml
<https://issues.redhat.com/browse/OPENJDK-256>
These four modules invoke "find" in their scripts:
1) jboss.container.java.s2i.bash
2) jboss.container.maven.s2i
3) jboss.container.s2i.core.bash
4) jboss.container.maven.default
1) depends upon 2) depends upon 3) & 4), but there's no
dependency relationship between 3) & 4).
Add a package dependency on "findutils" to 3) & 4).
If a container (such as ubi8/openjdk-8) uses both of 3) & 4),
the build process will attempt to install findutil twice. This
slows the build down, but is otherwise benign.
(Some other modules also invoke "find", but they are either
product specific or legacy modules, so I have not touched them.)
> [OPENJDK-256] Add findutils package dependency to some modules

- jboss/container/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh
From https://issues.redhat.com/browse/OPENJDK-242
The current Maven s2i build includes `-Dfabric8.skip=true` [1] but not `-Djkube.skip=true` [2]. JKube is the newer replacement for the fabric8 suite of tools. I think we should leave the `-Dfabric8.skip=true` for now as lots of existing workloads most likely still use this. Without this, an application wanting to use java s2i using Maven will have it's build blow up unless they add the environment variable `MAVEN_ARGS_APPEND=-Djkube.skip=true` to their build config. 
[1] https://github.com/jboss-openshift/cct_module/blob/master/jboss/container/maven/default/artifacts/opt/jboss/container/maven/default/maven.sh#L48
[2] https://www.eclipse.org/jkube/docs/openshift-maven-plugin#build-goal-configuration …
> [OPENJDK-242] [JavaS2I] Maven args doesn't contain -Djkube.skip=true

- jboss/container/maven/8.2.3.6.8/configure.sh
- jboss/container/maven/8.2.3.6.8/module.yaml
- jboss/container/maven/8.2.3.6/configure.sh
- jboss/container/maven/8.2.3.6/module.yaml
- jboss/container/maven/module/artifacts/maven.module
- jboss/container/maven/module/configure.sh
- jboss/container/maven/module/module.yaml
By providing /etc/dnf/modules.d/maven.module before attempting to
install Maven, we can get access to Maven 3.6 from the AppStream
repository without having to enable the module with full-fat DNF.
This means we can install Maven 3.6 with microdnf.
The maven.module file has to be in-place before attempting to install
Maven. Since CeKit processes "packages:" before "execute:" within the
context of a module, we need to put the new "execute:" stuff in a new
module that is depended upon by those that use "packages:" to install
maven.
> Enable maven AppStream module via conf file

- jboss/container/maven/8.2.3.6.8/module.yaml
- jboss/container/maven/default/bash/README.adoc
- jboss/container/maven/default/bash/configure.sh
- jboss/container/maven/default/bash/module.yaml
- jboss/container/maven/module/artifacts/maven.module
- jboss/container/maven/module/configure.sh
- jboss/container/maven/module/module.yaml
Maven 3.5 has reached EOL and requires upgrade.
https://issues.redhat.com/browse/CLOUD-3951
Signed-off-by: Daniel Kreling <dkreling@redhat.com>
> [CLOUD-3951] Bump default maven version to 3.6

- jboss/container/util/ubi-clean/configure.sh
- jboss/container/util/ubi-clean/module.yaml
This is a new module that removes a static list of RPMs.
The list of RPMs was determined by executing the following within the currently-shipped ubi8/openjdk-11, on a host without redhat entitlements (important): 
```
rpm -qa --queryformat "%{NAME}\n" \
| while read pkg; do microdnf repoquery $pkg 2>/dev/null | grep -q $pkg || echo $pkg; done
```
Unfortunately we cannot run this at container build-time, because it relies upon non-UBI RPMs not being in a configured dnf repository.
> ubi-clean module

- jboss/container/jolokia/7/module.yaml
- jboss/container/jolokia/8.2/module.yaml
https://issues.redhat.com/browse/CLOUD-4075
https://issues.redhat.com/browse/JBEAP-23179
Upgrade Jolokia to 1.7.1 to include fixes for JDK 9+
Signed-off-by: Tomas Hofman <thofman@redhat.com>
> [CLOUD-4075] Upgrade Jolokia to 1.7.1

- jboss/container/jolokia/api/module.yaml
- jboss/container/jolokia/bash/README.adoc
- jboss/container/jolokia/bash/module.yaml
https://issues.redhat.com/browse/CLOUD-4075
https://issues.redhat.com/browse/JBEAP-23179
Upgrade Jolokia to 1.7.1 to include fixes for JDK 9+
Signed-off-by: Tomas Hofman [thofman@redhat.com](mailto:thofman@redhat.com)
Downstream for https://github.com/jboss-openshift/cct_module/pull/415
> [0.39.x] CLOUD-4075 Upgrade Jolokia to 1.7.1

- jboss/container/prometheus/7/module.yaml
https://issues.redhat.com/browse/CLOUD-4176
Upgrade jmx_prometheus_javaagent to 0.3.2.redhat-00005 to include fixes for:
https://access.redhat.com/security/cve/CVE-2022-38752
https://access.redhat.com/security/cve/CVE-2022-41854
Signed-off-by: Ruben Novelli [rnovelli@redhat.com](mailto:rnovelli@redhat.com)
> CLOUD-4176 Upgrade jmx_prometheus_javaagent to 0.3.2.redhat-00005
