- os-bpmsuite-businesscentral/added/launch/bpmsuite-businesscentral.sh
- os-bpmsuite-businesscentral/added/openshift-launch.sh
- os-bpmsuite-businesscentral/configure.sh
- os-bpmsuite-executionserver/added/launch/bpmsuite-executionserver.sh
- os-bpmsuite-executionserver/added/openshift-launch.sh
- os-eap-launch/added/launch/maven-repos.sh
CLOUD-1844: Support External Maven Repos in EAP
https://issues.jboss.org/browse/CLOUD-1844
> CLOUD-1844: Support External Maven Repos in EAP

- os-eap71-openshift/added/standalone-openshift.xml
https://issues.jboss.org/browse/CLOUD-1907
> [CLOUD-1907] Reverted version changes

- os-bpmsuite-businesscentral/added/launch/bpmsuite-businesscentral.sh
Fix copy/paste typo in CLOUD-1844
https://issues.jboss.org/browse/CLOUD-1844
> Fix copy/paste typo in CLOUD-1844

- os-amq-launch/added/configure.sh
- os-amq-launch/added/drain.sh
- os-amq-launch/added/partitionPV.sh
- os-amq-launch/install.sh
- tests/features/amq/amq-common.feature
https://issues.jboss.org/browse/CLOUD-1952
> Initial message migration script updates: CLOUD-1952

- os-sso/added/openshift-launch.sh
- os-sso71/added/openshift-launch.sh
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-1965] [SSO7] Support clean shutdown on TERM

- os-bpmsuite-executionserver/added/launch/bpmsuite-executionserver.sh
- os-bpmsuite-executionserver/added/launch/kieserver-env.sh
- os-bpmsuite-executionserver/added/launch/kieserver-install.sh
- os-bpmsuite-executionserver/added/launch/kieserver-pull.sh
- os-bpmsuite-executionserver/added/launch/kieserver-verify.sh
- os-bpmsuite-executionserver/added/s2i/assemble
- os-bpmsuite-executionserver/configure.sh
CLOUD-1845: Support S2I in BPMS 7 KIE Server image
https://issues.jboss.org/browse/CLOUD-1845
> CLOUD-1845: Support S2I in BPMS 7 KIE Server image

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This adds or updates the Github PR template or CONTRIBUTING.md file for this
repository to reflect the versions in the master repository:
https://github.com/jboss-container-images/github-pr-template
This Pull Request was auto generated by the scripts from the above repository.
> Update GitHub PR template

- tests/features/datagrid/datagrid-authentication.feature
https://issues.jboss.org/browse/CLOUD-1981
> cloud-1981 fix broken auth ctf test for jdg65

- os-eap7-launch/added/openshift-launch.sh
- tests/features/eap/7/eap_7_shutdown.feature
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-1864] [EAP7] Support clean shutdown on TERM

- os-java-run/install_as_root
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [OpenJDK] Correct permissions of home directory

- os-jws-launch/added/launch/valve.sh
- os-jws7-conffiles/added/server-openshift.xml
- os-jws8-conffiles/added/server-openshift.xml
- tests/features/webserver/webserver_tomcat_variable_expansion.feature
> CLOUD-1814 RemoteIPValve always enabled

- os-datavirt/added/standalone-openshift.xml
- os-eap64-openshift/added/standalone-openshift.xml
- os-jdg-conffiles/added/clustered-openshift.xml
> CLOUD-2024 enable RemoteIpValve

- os-bpmsuite-executionserver/added/launch/bpmsuite-executionserver.sh
> GUVNOR-3430: Enable Kie server sync by default

- os-java-run/added/container-limits
- os-java-run/added/java-default-options
- tests/features/eap/eap_gc.feature
Recognize JAVA_CORE_LIMIT env var setting or replace it with CONTAINER_CORE_LIMIT in the documentation
> [CLOUD-1524] - Recognize JAVA_CORE_LIMIT

- os-java-hawkular/module.yaml
Signed-off-by: David Becvarik <dbecvari@redhat.com>
> fixed hawkular version

- os-amq-launch/added/readinessProbe.sh
> CLOUD-546 fix amq probe for disabled IPv6

- os-eap70-openshift/added/standalone-openshift.xml
- os-eap71-openshift/added/standalone-openshift.xml
> CLOUD-2055 add proxy-address-forwarding

- os-java-run/added/run-java.sh
- tests/features/java/java_s2i.feature
> CLOUD-2070 fix access to hsperfdata_jboss

- os-sso71/added/launch/add-sso-admin-user.sh
- os-sso71/added/launch/add-sso-realm.sh
- os-sso71/added/launch/datasource.sh
- os-sso71/added/launch/keycloak-spi.sh
- os-sso71/added/openshift-launch.sh
- os-sso71/added/standalone-openshift.xml
- tests/features/eap/eap_datasources.feature
- tests/features/eap/eap_resourceadapters.feature
> CLOUD-2044 add support for extensions and injected image mechanisms

- os-jdg-launch/added/openshift-launch.sh
- tests/features/datagrid/7.1/datagrid.feature
- tests/features/datagrid/datagrid.feature
This reverts commit 4ea1b39caf66e95576365ffbf4ec5fb5193253d1.
Conflicts:
tests/features/datagrid/datagrid.feature
> Revert "CLOUD-344 use standalone.sh to enable java debug"

- os-eap64-launch/added/launch/standalone.sh
- os-eap64-launch/added/openshift-launch.sh
- tests/features/eap/6.4/eap.feature
> CLOUD-237 move standalone.sh and standalone.conf mods to openshift image

- os-datavirt/added/openshift-launch.sh
- os-datavirt/added/standalone-openshift.xml
- os-eap-launch/added/launch/access_log_valve.sh
- os-jdg-conffiles/added/clustered-openshift.xml
- os-jdg-launch/added/openshift-launch.sh
- os-jdg7-conffiles/added/clustered-openshift.xml
- os-jdg7-launch/added/openshift-launch.sh
- os-sso71/added/openshift-launch.sh
> CLOUD-2054 configurable access log for all images

- os-eap7-openshift/added/standalone.conf
> CLOUD-2075 fix standalone.conf concat issue from lack of newline

- os-datavirt/added/launch/teiid.sh
- os-datavirt/configure.sh
- os-datavirt64/added/standalone-openshift.xml
- os-datavirt64/configure.sh
- os-datavirt64/module.yaml
- tests/features/datavirt/6.3/datavirt.feature
- tests/features/datavirt/6.4/datavirt.feature
- tests/features/datavirt/datavirt.feature
- tests/features/datavirt/datavirt_s2i.feature
- tests/features/datavirt/jgroups_encrypt.feature
> CLOUD-2067 JDV64 openshift image

- os-eap71-openshift/added/standalone-openshift.xml
> [CLOUD-2114] Removed redundant SSL config

- os-bpmsuite-executionserver/added/launch/bpmsuite-executionserver.sh
- os-eap-launch/added/launch/datasource-common.sh
@goldmann or @errantepiphany could you please take a look?
>  [CLOUD-2068] make refresh-interval for timer data-store configurable

- tests/features/amq/amq-common.feature
- tests/features/datavirt/datavirt.feature
- tests/features/decisionserver/decisionserver_6_3.feature
- tests/features/decisionserver/decisionserver_6_4.feature
- tests/features/eap/eap_common.feature
- tests/features/processserver/processserver_6_3.feature
- tests/features/processserver/processserver_6_4.feature
- tests/features/webserver/webserver_tomcat.feature
Signed-off-by: Marek Goldmann <mgoldman@redhat.com>
> Make sure the intitial scripts are executed before we test for ownership

- tests/features/eap/7/eap_7_messaging.feature
Signed-off-by: David Becvarik <dbecvari@redhat.com>
> Fixed typo in eap7 messaging test

- os-java-run/install_as_root
> [CLOUD-2121] - The /home/jboss directory is not writable by root group

- os-datavirt/configure.sh
- os-datavirt64/configure.sh
> [CLOUD-2119] - The /deployments directory is not writeable by root group

- tests/features/amq/6.3/amq.feature
Signed-off-by: Stanislav Knot <sknot@redhat.com>
> [AMQ63-1.2] Upgrade to rollup 5

- os-eap7-launch/added/launch/elytron.sh
- os-eap7-launch/added/launch/https.sh
- os-eap7-launch/added/openshift-launch.sh
- os-eap71-openshift/added/standalone-openshift.xml
- tests/features/eap/7.1/eap_7_1_https.feature
- tests/features/eap/7.1/eap_elytron_security_domains.feature
> Elytron config script

- tests/features/amq/6.2/amq.feature
> Removed AMQ tests moved to image repositories, make the other test generic

- os-bpmsuite-executionserver/added/launch/bpmsuite-executionserver.sh
> Add KieServer capabilities configuration

- os-amq-optional/install.sh
- os-amq-optional/module.yaml
- os-datavirt/added/standalone-openshift.xml
- os-datavirt64/added/standalone-openshift.xml
- os-eap64-launch/added/launch/ha.sh
- os-eap64-openshift/added/standalone-openshift.xml
- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-launch/added/launch/ha.sh
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
- os-eap70-openshift/added/standalone-openshift.xml
- os-eap71-openshift/added/standalone-openshift.xml
- os-jdg-conffiles/added/clustered-openshift.xml
- os-jdg7-conffiles/added/clustered-openshift.xml
- os-kieserver-launch/added/ha.sh
- os-kieserver-launch/added/kieserver-launch.sh
- os-kieserver-launch/configure.sh
- os-sso/added/standalone-openshift.xml
- os-sso71/added/standalone-openshift.xml
- tests/features/eap/eap_common.feature
> CLOUD-1958 add support for using openshift.DNS_PING to eap based images

- os-bpmsuite-businesscentral/added/launch/bpmsuite-businesscentral.sh
> [RHDM-305] - OutOfMemoryError: Metaspace in Decision central pod

- os-bpmsuite-smartrouter/added/openshift-launch.sh
> Update the value for the Running image to the same used in other images

- os-bpmsuite-businesscentral/added/openshift-launch.sh
- os-bpmsuite-executionserver/added/openshift-launch.sh
- os-bpmsuite-standalonecontroller/added/openshift-launch.sh
- tests/features/common.feature
Add the bxms to the access log tests
> Enable Access log for bxms7

- os-amq-launch/added/configure.sh
- os-amq-launch/added/openshift-login.config
- tests/features/amq/amq_auth.feature
> [WIP] CLOUD-298 ssl cert-based auth

- datagrid-openshift/added/probes/probe/jdg/jolokia.py
- datagrid7-openshift/added/probes/probe/jdg/jolokia.py
> CLOUD-451 add probe test for running caches

- os-datavirt/added/standalone-openshift.xml
- os-eap64-launch/added/launch/json_logging.sh
- os-eap64-openshift/added/standalone-openshift.xml
- os-eap7-launch/added/launch/json_logging.sh
- os-eap70-openshift/added/standalone-openshift.xml
- os-eap71-openshift/added/standalone-openshift.xml
- os-jdg-conffiles/added/clustered-openshift.xml
- os-jdg7-conffiles/added/clustered-openshift.xml
- os-sso/added/standalone-openshift.xml
- os-sso71/added/standalone-openshift.xml
- tests/features/eap/eap_logging.feature
> CLOUD-1517 configurable JSON logging

- os-jdg-launch/added/launch/infinispan-config.sh
- os-jdg7-launch/added/launch/infinispan-config.sh
- tests/features/datagrid/datagrid_distributed_cache.feature
> CLOUD-2043 add cache transaction configuration

- os-eap7-launch/added/launch/messaging.sh
- os-java-run/added/container-limits
- tests/features/eap/7/eap_7_messaging.feature
> CLOUD-2052 JAVA_CORE_LIMIT > CONTAINER_CORE_LIMIT

- os-java-run/added/run-java.sh
- tests/features/java/java_s2i.feature
> CLOUD-2070 fix perms for jstat

- os-eap64-hawkular/added/hawkular-javaagent-config.yaml
- os-eap70-hawkular/added/hawkular-javaagent-config.yaml
- os-java-hawkular/module.yaml
https://issues.jboss.org/browse/CLOUD-2081
> [CLOUD-2081] upgrade hawkular-agent jar 1.0.0.CR5 -> 1.0.1.Final

- os-eap64-launch/added/launch/datasource.sh
- os-eap7-launch/added/launch/datasource.sh
- tests/features/eap/eap_datasources.feature
> CLOUD-2111 support using extensions datasources as tx ObjectStore

- os-sso72/added/import-realm.json
- os-sso72/added/index.html
- os-sso72/added/launch/add-sso-admin-user.sh
- os-sso72/added/launch/add-sso-realm.sh
- os-sso72/added/launch/datasource.sh
- os-sso72/added/launch/keycloak-server-notruststore.json
- os-sso72/added/launch/keycloak-spi.sh
- os-sso72/added/openshift-launch.sh
- os-sso72/added/standalone-openshift.xml
- os-sso72/configure.sh
- os-sso72/module.yaml
New caches are introduced in 7.2.0, and the server fails to boot without them.
> RHSSO-1210 Copy os-sso71 to os-sso72 and modify xml for new caches

- os-sso72/added/launch/openshift-common.sh
- os-sso72/added/openshift-launch.sh
- os-sso72/added/openshift-migrate.sh
- os-sso72/added/standalone-openshift.xml
- os-sso72/configure.sh
- os-sso72/module.yaml
Updating PR #168 with changes that were made to 71 since the PR was filed.
> Sync os-sso72 with os-sso71's changes

- os-java-jolokia/module.yaml
> CLOUD-2314 bump jolokia to 1.5.0

- dynamic-resources/dynamic_resources.sh
- os-java-run/added/java-default-options
- tests/features/amq/amq-common.feature
- tests/features/amq/amq_gc.feature
- tests/features/eap/eap_gc.feature
- tests/features/eap/eap_s2i.feature
- tests/features/java/gc.feature
- tests/features/webserver/webserver_tomcat.feature
- tests/features/webserver/webserver_tomcat_gc.feature
- tests/features/webserver/webserver_tomcat_s2i.feature
> CLOUD-1537 optimize JVM GC settings for containers

- os-amq-optional/install.sh
- os-amq-optional/module.yaml
- os-eap64-ping/configure.sh
- os-eap64-ping/module.yaml
- os-eap7-ping/configure.sh
- os-eap7-ping/module.yaml
> CLOUD-2360 update openshift-ping to 1.2.1.Final

- os-jdg7-launch/added/launch/infinispan-config.sh
* All uppercase
* Replace '-' (dash) with '_' (underscore)
Signed-off-by: Osni Oliveira <osni.oliveira@gmail.com>
JIRA issue: https://issues.jboss.org/browse/CLOUD-2299
> [CLOUD-2299] Sanitize the env variable names created from cache names

- os-datavirt64-dsb/added/standalone-openshift.xml
- os-datavirt64-dsb/configure.sh
- os-datavirt64-dsb/module.yaml
> [CLOUD-2318] created new module for DSB tech preview image

- os-eap7-launch/added/launch/activemq-subsystem.xml
https://issues.jboss.org/browse/CLOUD-2339
> CLOUD-2339 Apply WFLY-8494 messaging-activemq config settings to EAP7 images

- os-eap-launch/added/launch/datasource-common.sh
https://issues.jboss.org/browse/CLOUD-2366
> CLOUD-2366 - fix default datasource

- os-sso72/added/launch/openshift-x509.sh
> [CLOUD-2436] Don't auto-generate the JGroups keystore if JGROUPS_ENCRYPT_SECRET variable was provided

- os-eap-launch/added/launch/maven-repos.sh
- os-eap-launch/tests/bats/expectations/profile_all_vars.xml
- os-eap-launch/tests/bats/expectations/profile_custom_discovery.xml
- os-eap-launch/tests/bats/expectations/profile_default.xml
- os-eap-launch/tests/bats/expectations/profile_default_discovery.xml
- os-eap-launch/tests/bats/expectations/profile_repo1.xml
- os-eap-launch/tests/bats/expectations/profile_repo2.xml
- os-eap-launch/tests/bats/expectations/server.xml
- os-eap-launch/tests/bats/expectations/server_repo1.xml
- os-eap-launch/tests/bats/expectations/server_repo2.xml
- os-eap-launch/tests/bats/expectations/server_with_all.xml
- os-eap-launch/tests/bats/expectations/server_with_privatekey.xml
- os-eap-launch/tests/bats/expectations/server_with_username.xml
- os-eap-launch/tests/bats/maven-repos-add-repo.bats
- os-eap-launch/tests/bats/maven-repos-add-server.bats
- os-eap-launch/tests/bats/maven-repos-common.bash
- os-eap-launch/tests/bats/maven-repos-configure.bats
- os-eap64-launch/added/launch/launch-common.sh
- os-eap64-launch/tests/bats/launch-common.bats
- os-eap7-launch/added/launch/launch-common.sh
- os-eap7-launch/tests/bats/launch-common.bats
- tests/bats/README.md
- tests/bats/common/xml_utils.bash
Fixes https://issues.jboss.org/browse/CLOUD-2484
* Adds unit tests using Bats
* Refactors existing code
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
> [CLOUD-2484] Refactor maven-repos.sh and include unit tests

- os-eap64-launch/added/launch/jboss_modules_system_pkgs.sh
- os-eap7-launch/added/launch/jboss_modules_system_pkgs.sh
https://issues.jboss.org/browse/CLOUD-2501
> add com.sun.crypto.provider to JBOSS_MODULES_SYSTEM_PKGS

- os-jdg7-launch/added/launch/openshift-common.sh
Enables JDG 7.x to use the fix for [CLOUD-2501](https://issues.jboss.org/browse/CLOUD-2501).
See #238.
Signed-off-by: Osni Oliveira <osni.oliveira@gmail.com>
> [CLOUD-2501] Add modules system pkgs script to JDG 7.x - sprint-16

- os-jdg7-launch/added/launch/openshift-common.sh
Enables JDG 7.x to use the fix for [CLOUD-2501](https://issues.jboss.org/browse/CLOUD-2501).
Signed-off-by: Osni Oliveira <osni.oliveira@gmail.com>
> [CLOUD-2501] Add modules system pkgs script to JDG 7.x

- os-eap-probes/added/probes/probe/api.py
> CLOUD-2456 Make probe Status Enum sortable

- tests/features/eap/CD12/eap_cd12.feature
- tests/features/eap/CD12/eap_cd12_datasources.feature
- tests/features/eap/CD12/eap_cd12_https.feature
- tests/features/eap/CD12/eap_elytron_security_domains.feature
- tests/features/eap/eap_common.feature
- tests/features/eap/eap_datasources.feature
- tests/features/eap/eap_gc.feature
- tests/features/eap/eap_hawkular.feature
- tests/features/eap/eap_logging.feature
- tests/features/eap/eap_resourceadapters.feature
- tests/features/eap/eap_s2i.feature
- tests/features/eap/eap_security_domains.feature
- tests/features/eap/eap_sso.feature
- tests/features/eap/eap_variable_expansion.feature
https://issues.jboss.org/browse/CLOUD-2512
> CLOUD-2512 - EAP-CD CTF tests

- os-eap-logging/configure.sh
- os-eap-logging/module.yaml
https://issues.jboss.org/browse/CLOUD-2420
> CLOUD-2420 - LogstashFormatter does not handle nested "Caused by" logs correctly

- os-eap-launch/added/launch/access_log_valve.sh
https://issues.jboss.org/browse/CLOUD-2391
> CLOUD-2391 Fixed REST access logging

- os-java-run/added/proxy-options
> CLOUD-2084 remove quotes from http.nonProxyHosts value

- os-sso71/added/launch/openshift-common.sh
- os-sso72/added/launch/openshift-common.sh
> [CLOUD-2547] Don't execute the Access Log Valve configuration script two times

- tests/features/datagrid/datagrid_variable_expansion_https.feature
- tests/features/eap/eap_resourceadapters.feature
https://issues.jboss.org/browse/CLOUD-2569
> CLOUD-2569 - drop @wip in cct_module tests

- os-eap64-sso/configure.sh
- os-eap64-sso/module.yaml
- os-eap70-sso/configure.sh
- os-eap70-sso/module.yaml
> [CLOUD-2295] Update RH-SSO client and SAML adapters to the RH-SSO 7.2.2 ones

- tests/features/eap/eap_datasources.feature
> CLOUD-2527 - missing EAP CD tests

- os-eap7-launch/added/launch/elytron.sh
- os-eap7-launch/added/launch/https.sh
> [CLOUD-2438] Enable proxy-address-forwarding by default on HTTPS listener too

- os-jdg7-launch/added/launch/infinispan-config.sh
https://issues.jboss.org/browse/CLOUD-2362
> CLOUD-2362 Fix typo

- os-eap-activemq-rar/module.yaml
https://issues.jboss.org/browse/CLOUD-2663
> [EAP] upgrade activemq-rar to activemq-rar-5.11.0.redhat-630347.rar

- os-eap-logging/module.yaml
https://issues.jboss.org/browse/CLOUD-2706                                                                
Signed-off-by: Ken Wills <kwills@redhat.com> 
> [CLOUD-2706] - deprecate os-eap-logging in favor of https://github.com/jboss-container-images/jboss-eap-modules/

- os-eap-logging/module.yaml
> [CLOUD-2706] - fix use of : in comment.

- os-java-run/added/run-java.sh
We already document this in the module conf file...
https://issues.jboss.org/browse/CLOUD-2435
> (Re-?)add support for JAVA_OPTS_APPEND

- os-eap7-launch/added/launch/filters.sh
- os-eap7-launch/added/launch/openshift-common.sh
- os-eap70-openshift/added/standalone-openshift.xml
- os-eap71-openshift/added/standalone-openshift.xml
- tests/features/eap/7/eap_7_filters.feature
[CLOUD-2877] Provide response header filter support in EAP 7
https://issues.jboss.org/browse/CLOUD-2877
Signed-off-by: David Ward <dward@redhat.com>
> [CLOUD-2877] Provide response header filter support in EAP 7

- jboss/container/maven/default/bash/artifacts/opt/jboss/container/maven/default/jboss-settings.xml
> Correct repository.jboss.container.org->repository.jboss.org

- os-jws-launch/added/launch.sh
- tests/features/webserver/webserver_tomcat7.feature
- tests/features/webserver/webserver_tomcat8.feature
> CLOUD-2747 fix http.nonProxyHosts escaping for jws

- os-eap7-launch/added/launch/filters.sh
https://issues.jboss.org/browse/CLOUD-2892
> CLOUD-2892 [EAP CD] Update EAP CD configs to support filters

- os-eap7-openshift/prepare.sh
https://issues.jboss.org/browse/CLOUD-2929
> Avoid creating /deployments/deployments if /deployments already exists

- os-eap-sso/added/keycloak.sh
Signed-off-by: Ruben Romero Montes <rromerom@redhat.com>
Fix https://issues.jboss.org/browse/CLOUD-2912
> [CLOUD-2912] Do not set AUTO_DEPLOY_EXPLODED for SSO integration

- jboss/container/openjdk/jdk/8/configure.sh
> Correct path for JDK chmod

- tests/features/sso/sso.feature
> Fix SSO tests for EAP 7.2 changes

- jboss/container/openjdk/jdk/11/configure.sh
- jboss/container/openjdk/jdk/11/module.yaml
- jboss/container/openjdk/jdk/8/configure.sh
- jboss/container/openjdk/jdk/8/module.yaml
> CLOUD-3004 /dev/urandom not configured for JDK 11

- jboss/container/eap/prometheus/agent/README.adoc
- jboss/container/eap/prometheus/agent/configure.sh
- jboss/container/eap/prometheus/agent/module.yaml
- jboss/container/eap/prometheus/agent/src/standalone.conf
- jboss/container/eap/prometheus/config/6.4/README.adoc
- jboss/container/eap/prometheus/config/6.4/artifacts/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
- jboss/container/eap/prometheus/config/6.4/configure.sh
- jboss/container/eap/prometheus/config/6.4/module.yaml
- jboss/container/eap/prometheus/config/7.1/README.adoc
- jboss/container/eap/prometheus/config/7.1/artifacts/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
- jboss/container/eap/prometheus/config/7.1/configure.sh
- jboss/container/eap/prometheus/config/7.1/module.yaml
- jboss/container/java/s2i/bash/artifacts/usr/local/s2i/run
- jboss/container/java/s2i/bash/module.yaml
- jboss/container/prometheus/api/README.adoc
- jboss/container/prometheus/api/module.yaml
- jboss/container/prometheus/bash/README.adoc
- jboss/container/prometheus/bash/artifacts/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml
- jboss/container/prometheus/bash/artifacts/opt/jboss/container/prometheus/prometheus-opts
- jboss/container/prometheus/bash/configure.sh
- jboss/container/prometheus/bash/module.yaml
- jboss/container/prometheus/bash/tests/features/prometheus.feature
> CLOUD-3013 add basic prometheus modules

- jboss/container/proxy/api/module.yaml
> fix minor typos

- .github/PULL_REQUEST_TEMPLATE.md
This adds or updates the Github PR template or CONTRIBUTING.md files for this
repository to reflect the current versions in the master repository:
https://github.com/jboss-container-images/github-pr-template
This Pull Request was auto generated by the scripts from the above repository.
> Update GitHub PR template and/or CONTRIBUTING.md

- os-sso72/module.yaml
Repositories should be defined on image level.
FYI @iankko
> Remove repository definition from modules

- os-jws-db-drivers/run
https://issues.jboss.org/browse/CLOUD-3261
https://issues.jboss.org/browse/CLOUD-3262
Signed-off-by: Sokratis Zappis <szappis@redhat.com>
> [CLOUD-3261] (JWS31) Update mongodb driver to mongodb36, [CLOUD-3262] (JWS50) Update mongodb driver to mongodb36

- jboss/container/jolokia/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3309
> CLOUD-3309 - Update jolokia to 1.6.2

- jboss/container/jolokia/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3312
Signed-off-by: Roberto Oliveira rguimara@redhat.com
> [CLOUD-3312] Update jolokia to 1.6.2

- jboss/container/jolokia/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3311
Signed-off-by: Roberto Oliveira rguimara@redhat.com
> [CLOUD-3311] Update jolokia to 1.6.2

- dynamic-resources/module.yaml
> Fix old module ref

- jboss/container/hawkular/bash/module.yaml
- jboss/container/prometheus/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3377
Signed-off-by: Ken Wills <kwills@redhat.com
> Fix hawkular & prometheus fetch from brew

- jboss/container/jolokia/bash/module.yaml
https://issues.jboss.org/browse/CLOUD-3379
> [CLOUD-3379] - genericize jolokia module name

- jboss/container/openjdk/jdk/openj9-11/module.yaml
- jboss/container/openjdk/jdk/openj9-8/module.yaml
Update $JAVA_HOME for openj9 to jdk folders to reduce the confusion.
> Update JAVA_HOME for openj9 containers

- jboss/container/util/pkg-update/execute.sh
- jboss/container/util/pkg-update/module.yaml
Performs a package update (yum, or dnf, or microdnf)
> [OPENJDK-123] pkg-update module

- jboss/container/java/s2i/bash/module.yaml
- tests/features/jolokia.feature
https://issues.redhat.com/browse/OPENJDK-37
> [Openjdk-37] drop jolokia from OpenJDK images

- jboss/container/maven/8.2.3.6.8/configure.sh
- jboss/container/maven/8.2.3.6.8/module.yaml
- jboss/container/maven/8.2.3.6/configure.sh
- jboss/container/maven/8.2.3.6/module.yaml
/usr/bin/mvn complains about the missing file.
> Blank maven.conf file instead of removing it

- jboss/container/prometheus/bash/module.yaml
https://issues.redhat.com/browse/CLOUD-3923
> CLOUD-3923 update prometheus-jmx-exporter to 0.3.2

- jboss/container/prometheus/bash/module.yaml
https://issues.redhat.com/browse/CLOUD-3923
> [CLOUD-3923] - Update prometheus (fix typo)

- jboss/container/java/jvm/bash/artifacts/opt/jboss/container/java/jvm/java-default-options
https://issues.redhat.com/browse/JBEAP-18968
> [CLOUD-3964] Do not set a default metaspace max value

- jboss/container/s2i/core/api/module.yaml
- jboss/container/s2i/core/bash/artifacts/opt/jboss/container/s2i/core/s2i-core
cherry-pick of: https://github.com/wildfly/wildfly-cekit-modules/pull/235
> Fix for CLOUD-3977, Deleting src dir after s2i breaks WildFly image with ODO
